### ISSUE TITLE
Autodetect does not work with Streebog/Twofish

### ISSUE THREAD

**Issue by Rannek** [veracrypt/VeraCrypt#1027] opened 2023-01-17 21:13 UTC
Autodetect does not work with Streebog/Twofish algo. It works only with manually selecting Streebog.
# Expected behavior

Autodetecting the volume
# Observed behavior

Error Even with the right password.
# Steps to reproduce

1. Create a new volume
2. Set encryption algo to Twofish and Hash algo to Streebog.
3. Try to mount the volume with autodetection and the right password: Error
4.Try to mount the volume with HMAC Streebog selected: Success 

# Screenshots

# Your Environment

Please tell us more about your environment

**VeraCrypt version:** 
1.25.9 Linux 64 bit
**Operating system and version:** 

**System type:**

**Comment by kokokodak** [comment] 2023-08-01 15:05
Hi, I am not able to reproduce, on 64 bit Linux. Created the volume with Twofish and HMAC-Streebog, mount with Autodetect has been successful. Do you still see this issue? Does it happen every time (to rule out typo in password etc)?

**Comment by kokokodak** [comment] 2023-08-01 15:05
Hi, I am not able to reproduce, on 64 bit Linux. Created the volume with Twofish and HMAC-Streebog, mount with Autodetect has been successful. Do you still see this issue? Does it happen every time (to rule out typo in password etc)?

**Comment by Rannek** [comment] 2023-08-01 15:47
Hi there! Strangely, now i tried replicate it again and now it works. I
don't know what caused that bug back then, but the autodetect function
somehow not worked. I will update it with further details if i find that
bug again.

Kokokodak (TTM) ***@***.***> ezt írta (időpont: 2023. aug.
1., K, 17:05):

**Comment by kokokodak** [comment] 2023-08-01 16:21
Thanks for information. I've checked the code, but didn't find anything that would hint what could have gone wrong. You can consider closing the issue and raising it again in case you face that problem again.

**Closed** 2023-08-01 22:57 UTC
Labels: bug
