### ISSUE TITLE
System favorite volume not automatically mounted on boot

### ISSUE THREAD

**Issue by 0x8DEADF00D** [veracrypt/VeraCrypt#8] opened 2015-03-14 19:06 UTC
Thank your for all your effort going into this great project. I have an issue with the system favorite volume implemention. If I add one of my volumes that contain encrypted VeraCrypt containers and select the setting "Mount system favorite volumes when Windows starts [...]" the container actually doesn't get mounted. The drive is correctly listed but here is a screenshot, just in case you need something specific:

![Screenshot](http://i.epvpimg.com/dHrBb.png)

`D` is the volume and `DATA` is the container.

I'd like to have this implemented because I'm using a second internal hard drive that I'm mounting every time Windows has booted.

**Comment by idrassi** [comment] 2015-03-14 22:23
The System Favorites feature works and has been tested on several configuration. This is one of the top feature of VeraCrypt.

In your case, there are two possible explanations:
* Automatic mount is disabled on Windows: I answered a similar question on Sourceforge where I suggested to use **diskpart** to enable automount: <https://sourceforge.net/p/veracrypt/discussion/technical/thread/5948980c/?limit=25#106d>. Can you try this?
* Password mismatch: the password of the System Favorite must be the same as the boot encryption password. Moreover, the boot encryption password is required to be typed using US keyboard layout (BIOS requirement. VeraCrypt automatically switched the password edit control to US layout when specifying the boot password). This means that the System Favorite password can be different even you type the same keys on the keyboard which may explain the failure to mount. For example, let's suppose that you are using the German keyboard layout by default and that you typed the following keys as they appear on the keyboard when specifying the boot password: 'Q' 'W' 'E' 'R' 'T' 'Z'. Since layout is automatically switched to US in order to match the BIOS layout, the **effective password** is QWERT**Y**. As you notice, the last letter is different from what is displayed on the keyboard. On the other hand, when you create a normal container, VeraCrypt uses the current layout and so if you type as before 'Q' 'W' 'E' 'R' 'T' 'Z', the effective password will be QWERTZ (the last letter is as expected). In this configuration, this container will not work as a System Favoritie since the two passwords mismatch. One possible solution is to use Notepad to type your boot password after manually switching the keyboard layout to US and then change the container password using the displayed value. Another solution is to use a password that is invariant between your native layout and the US layout (by using keys that map to the same value on the two layouts).
* Drive letter not available: check that the L drive letter is not already assigned by Windows.

Let's know if any of this solves your issue.

**Comment by Mostey** [comment] 2015-03-15 11:35
> Moreover, the boot encryption password is required to be typed using US keyboard layout

Indeed, that seems to be the cause. I got some special characters in my password that vary between German and US layouts. However, may you please include some hints (or a check box/extra dialog in the password form for containers that can be enabled/disabled to automatically convert the used layout to the US layout - just as you do for the boot password) to clarify things? The workaround suggested really isn't comfortable and can be prevented this way, I guess?

Unfortunately I didn't find anything in the documentation about that issue. (If this is mentioned somewhere I would suggest to highlight it or something like that)

Thanks for your help, I will try the workaround asap.

**Comment by Mostey** [comment] 2015-03-17 17:10
Your workaround did work the last 2 days but for some reason, it didn't mount the volume on my last boot. Are you aware of any issues that influence this feature?

**Comment by idrassi** [comment] 2015-03-17 20:21
Well...this is very strange! I don't see a reason why a volume will stop being mounted if the same inputs are provided each time. Something must have changed or some other software was added that may have this impact.

**Comment by Mostey** [comment] 2015-03-17 21:12
I recently changed the label of the volume. But that shouldn't affect anything, should it?

**Comment by idrassi** [comment] 2015-03-17 22:20
No, the label has no effect on the mount operation. Maybe the drive letter is already taken when you boot? Did you try changing the drive letter to a different value?
As I said before, I don't see how VeraCrypt could suddenly stop mounting the volume if everything is the same as before...this defies logic.

**Comment by Mostey** [comment] 2015-03-18 16:40
> Maybe the drive letter is already taken when you boot?
Nope.

Well as I booted up my windows like 5 minutes ago, the volume wasn't mounted again. I readded the volume to the system favorite volumes and now everything works just fine. However, the problems started when I changed the volume label...

Anyways, thank you for your help - I guess that won't happen again since I don't have any reason to change something in my VeraCrypt volume again. I will close this for now.

**Comment by Mostey** [comment] 2015-06-17 18:11
I'm back with the same issue. I even reinstalled my windows one more time to eliminate that this issue is caused by some other software.

Sometimes the volume get's mounted and sometimes it does not. Changing the letter also didn't help, my drive is now mounted as Y instead of L.

**Comment by idrassi** [comment] 2015-06-21 12:20
Hi,

Without any other information, I can't help on understanding why it sometimes fail and sometimes succeed.
Can you please check the Windows Event Viewer to see if there is any special error or warning logged when the failure occur?
Is the drive on which the file contain exist a fixed drive or a removable one? Maybe sometime the file is not accessible at boot since VeraCrypt tries to load the system favorite at the very beginning of Windows startup: a possibility is that the drive where the file container is located is not ready yet.

**Comment by Mostey** [comment] 2015-06-21 12:55
Thank you for your reply, apart from a DCOM error in the system event log I can't see any other errors or warnings that occur in the booting timeframe. However, the DCOM error seems to be not related to VeraCrypt.

> Is the drive on which the file contain exist a fixed drive or a removable one?

It is a fixed drive that is always guaranteed to be available on boot.

> Maybe sometime the file is not accessible at boot since VeraCrypt tries to load the system favorite at the very beginning of Windows startup: a possibility is that the drive where the file container is located is not ready yet.

That may be the case. I guess we have some race condition here but unfortunately I can't help you further with debugging because I have no idea how things work at such a low level.

I'm running Windows 8.1 64 Bit if that matters somehow.

**Comment by noutritenou** [comment] 2015-07-10 05:21
Hi, I have the same problem.  With me, the system favorite drive does not mount on the first boot after the computer has been off for a while.  So I restart and then it mounts.  This was my daily morning routine on a different computer as well - which used TrueCrypt.

In the beginning, the TrueCrypt computer wasn't consistent - sometimes it would boot the fav. drive on first try, other times it would need more than one restart to get it.  The VeraCrypt computer has however so far been consistent that it will not mount on 1st boot and will mount on 2nd boot.

Just fyi.

**Comment by idrassi** [comment] 2015-07-10 07:55
Thank for you @noutritenou for reporting this.
In order to compare with the other report, is it possible for you to check the Windows Event Viewer logs when the mount fails to see if you have any error or warning entry? 
Also, is the system favorite drive a fixed one or a removable one? 
And finally, are you also running Windows 8.1 64-bit?

Thank you in advance.

**Comment by noutritenou** [comment] 2015-07-11 05:44
Yes, running Windows 8.1 64-bit.
It is a removable drive.

I looked in Event Viewer, but didn't see any relevant errors or warnings on startup.  I do get an error, which I'm guessing is not very relevant, apparently on every shutdown if the drive is mounted: "The default transaction resource manager on volume J: encountered a non-retryable error and could not start.  The data contains the error code."  (I thought I would try to dismount the drive before shutting down, but got notified that files/folders are in use, even though it has no files on it.  (File History is set up to use the drive but has never been turned on.)  So I just left it mounted and will keep getting the error, I presume.)

For what it's worth, just now I just did two consecutive shutdowns (as opposed to restarts), and the drive did not mount either time.  I then restarted the computer twice in a row, and the drive mounted both times.

**Comment by Mostey** [comment] 2015-07-11 09:55
>  I just did two consecutive shutdowns (as opposed to restarts), and the drive did not mount either time. I then restarted the computer twice in a row, and the drive mounted both times.

I can confirm this. Currently the chance that the drive is mounted from a cold start is at about 10%. A restart seems to always mount the drive.

**Comment by idrassi** [comment] 2015-07-11 14:03
These are interesting results. This definitely means that the drive requires some extra time to "warm up" in a case of a cold boot whereas during restart the drive is already up and running.

This means that VeraCrypt encounters an error when trying to access the drive after the cold boot, which stops the mounting process.
Unfortunately, in the current code we don't retry mounting in case of failure. A possible solution will be to retry the mounting few seconds later. I'll see how to implement this mechanism and I'll keep you informed.

**Comment by idrassi** [comment] 2015-07-12 00:07
I have implement a retry after 10 seconds of a failure to mount system volumes. You can get it from the Nightly builds folder on Sourceforge: https://sourceforge.net/projects/veracrypt/files/VeraCrypt%20Nightly%20Builds/
Can you try and see if it makes things better on your side?

FYI, this is a stable build for the upcoming 1.12. it is still in beta because some GUI enhancements must done on the new [PIM feature](https://veracrypt.codeplex.com/wikipage?title=Personal%20Iterations%20Multiplier%20%28PIM%29). In you are using 1.0f-2, just use an empty PIM.

**Comment by noutritenou** [comment] 2015-07-12 06:46
Thank you!  I installed the nightly build (VeraCrypt Setup 1.12-BETA.exe), but unfortunately, I can't see a difference.  I tried two cold boots, fav. drive did not mount.  I then did a restart, and it mounted.

**Comment by idrassi** [comment] 2015-07-12 06:57
Actually I was about to write a new post when you answered! I wanted to say that I came up with a better fix and that I will upload a new setup.
Your result confirm my own evaluation of the fix since it didn't cover all cases. I believe the new fix is a more general one that should solve your issue.
Can you please give it a try?
The new 1.12-BETA binary is available at Sourceforge [Nightly Builds](https://sourceforge.net/projects/veracrypt/files/VeraCrypt%20Nightly%20Builds/) folder (file version 1.12.14).

Thank you in advance for your feedback.

**Comment by noutritenou** [comment] 2015-07-12 08:14
Thanks again, much appreciated.  Sorry to say the problem is stubborn, I still get the same behavior with 1.12.14.

**Comment by idrassi** [comment] 2015-07-12 13:32
humm...strange.

I have added some extra Event logs in order to understand what kind of errors are happening in your case. Can you please install the new 1.12-BETA binary (version 1.12.15) that I have just uploaded to Sourceforge and try again?
This time, go to Windows Event Viewer and under "Windows\Applications", you will find error entries with source set to "VeraCryptSystemFavorites". On each event, go to "Details". Please post all events and their details.
It will look like the screenshot below.

![VeraCryptServiceEventLog](https://i.imgur.com/KLUQPn4.png)

By the way, I also did a modification to correctly initialize a global variable. There is a very small chance that this was the cause of the issue so don't be surprise if it works (although I doubt).

Thank you again for your valuable help. This definitely will make VeraCrypt a more reliable software.

**Comment by noutritenou** [comment] 2015-07-12 14:40
I installed version 1.12.15.  After a cold boot, as expected the drive didn't mount, but as you can see, there are no VeraCrypt errors in the log (the time here is 21:30, so the last error was from another application more than 8 hours ago).  I also looked at non-error events, but there were none from VeraCrypt in that log.

![no veracrypt errors](https://cloud.githubusercontent.com/assets/5758750/8638211/f17dfa80-28dd-11e5-8bc9-222b99a9bb79.png)

**Comment by idrassi** [comment] 2015-07-12 15:08
I guess you filter messages to show only errors because there are always other messages in the Application logs that are not errors.

I add informative logs this time so that we trace the execution steps. These are guaranteed to be present.
I uploaded a new setup with this small modification. Thank you again for your feedback on this. Definitely, this time we'll know what's happening thank to these new informative messages (don't filter on errors this times).

![veracrypt_eventlogs_systemfavorites](https://cloud.githubusercontent.com/assets/4698669/8638348/8a646390-28b8-11e5-9d3a-f535f38013fb.PNG)

**Comment by noutritenou** [comment] 2015-07-12 15:46
Now there are Information events from VeraCrypt.  But only from the restart (which I did after upgrading VeraCrypt).  After the restart, I did a cold boot, but there are no entries from VeraCrypt from it.

![1](https://cloud.githubusercontent.com/assets/5758750/8638496/7200f6b8-28e7-11e5-833b-682e850a690a.png)

![2](https://cloud.githubusercontent.com/assets/5758750/8638494/71fea476-28e7-11e5-9b09-8bd604681d60.png)

![3](https://cloud.githubusercontent.com/assets/5758750/8638497/7201ed84-28e7-11e5-9a76-13b54f6c44d0.png)

![4](https://cloud.githubusercontent.com/assets/5758750/8638495/71ff6208-28e7-11e5-822b-cf30b29b3821.png)

![5](https://cloud.githubusercontent.com/assets/5758750/8638498/72064078-28e7-11e5-9d19-fc0838cce06c.png)

**Comment by idrassi** [comment] 2015-07-12 15:51
OK. For VeraCrypt event, the "Details" panel is more helpful since it contains the actual messages :-)

If after the cold boot there are no entries for VeraCrypt, this means that the VeraCrypt services responsible for mounting System Favorites is not started at all!! This kind of weird...

Did you see if there are no errors or warning on the "System" events log during a cool boot? Maybe there could be an entry that may explain why the service VeraCryptSystemFavorites didn't start.

**Comment by noutritenou** [comment] 2015-07-12 16:15
There are no errors or warnings in the System event log during the cold boot, only information events.  (I am not sure why it says it returned from a low power state there, as I selected Shutdown from the power menu in the charms bar, and saw a regular boot.)  Shutdown was at 22:24, boot at 22:27.

![system log](https://cloud.githubusercontent.com/assets/5758750/8638620/2a9426c0-28eb-11e5-87c2-bf69ca10b213.png)

**Comment by idrassi** [comment] 2015-07-12 16:24
Windows 8 introduced something called "Hybrid boot and shutdown" to give users the impression that booting is quick, so I'm wondering if actually all of this is caused by:
- you perform the hybrid shutdown which logs you off and caused the system favorite to dismount
- you perform the hybrid boot and the system favorite remains dismounted since your Windows didn't actually shutdown and then start again.

Just to check if this is the case, can you disable this feature as explained [here](https://www.maketecheasier.com/disable-hybrid-boot-and-shutdown-in-windows-8) and then try again?
Anyway, this would explain all the strange things...

Another way to solve this issue is to configure the System Favorites to be dismounted only by Administrative privileges (the favorite will still be usable by anyone). Open the Manage System Favorite dialog and check the option at the buttom.
![SysFavAdmin](https://i.imgur.com/9oAvz5j.png)

**Comment by noutritenou** [comment] 2015-07-12 17:16
You solved it!  :-)  I disabled fast startup, and now the drive mounted upon a cold boot.  I knew windows 8 boasted fast boots, but I didn't know they did it this way, then I would have disabled it before.

Thank you so much for figuring this out.  I hope the lesson learned can fit in the user guide somewhere to benefit others.

![fast startup](https://cloud.githubusercontent.com/assets/5758750/8638947/3be3087a-28f4-11e5-8d24-dd97c9dfa0e8.png)

**Comment by idrassi** [comment] 2015-07-12 17:30
Microsoft uses this kind of tricks for marketing purposes but they introduce many issues by doing so...especially on the security side!

You're right. this must be mentionned in the documentation. I have added a note about it to the "Limitations" section of the documentation: https://veracrypt.codeplex.com/wikipage?title=Issues%20and%20Limitations

Thanks for your helping understand this.

**Comment by Mostey** [comment] 2015-07-12 17:48
Great, I will try this out. Thank you @idrassi for taking your time to resolve this issue and thank you @noutritenou for assisting and coming up with the same issue here.

**Comment by noutritenou** [comment] 2015-07-13 10:42
Curiously, even with fast startup disabled, my computer with TrueCrypt does the same thing - only mounts fav. drive on restarts, not on cold boots.  Just an fyi, thought it was worth mentioning.

**Comment by idrassi** [comment] 2015-07-13 13:07
I think there are two issues here: the first is Windows 8 hybrid boot/shutdown and the second is the delay for the favorite drive to be recognized by Windows.

TrueCrypt must be affected by the second issue for which I implemented a fix in VeraCrypt that consists on retrying to mount such "missing" system favorites a number of times (4 times), sleeping 5 seconds after each failed attempt.

**Comment by idrassi** [comment] 2015-08-30 23:23
Closing this ticket since version 1.13 released on August 9th 2015 implements a mechanism to ensure that system favorites are always mounted at boot time.

**Closed by idrassi** 2015-08-30 23:23 UTC

**Comment by SM411** [comment] 2015-09-11 14:29
I just want to update my experience. I been running 1.13, and had same issue (not mounting on cold boot, mounting on restart). It was fixed by disabling fast boot (Windows 10).

**Comment by mnn** [comment] 2015-09-25 05:57
Failed mount of system favourite partition (on same drive as system part.) happened to me as well. I'm running version 1.14 on win 10 x64. It was a start (not restart), but only happened once in ~10 attempts. I think Windows was applying updates.

**Comment by eyeson** [comment] 2015-10-10 12:00
Running 1.16 and every 1 out of 4 boots, VeraCrypt will fail to mount my D drive (system favourite partition using the same password - as proved by the fact it will normally work more times than not)

**Comment by draconus** [comment] 2016-11-06 10:52
I confirm that in 1.19 problem persists for Win10Home and that it can be solved by disabling fast boot from power menu.

**Comment by tobiasstraub** [comment] 2017-02-22 20:54
I can confirm that disabling "fast startup" solves the problem. Since "fast startup" is default in Windows 10, I think the problem solution should be better promoted within VeraCrypt.

**Comment by xpac1985** [comment] 2017-03-15 20:01
@idrassi Recommend to re-open this issue, as the problem exists with Windows 10 (Enterprise, in my case).
Maybe displaying a popup on first use of auto-mount (system favourites) could help.
Posting here, as this is still the first Google search result for me.

**Comment by RcTomcat** [comment] 2017-06-26 20:07
just had the same problem on windows 10 enterprise. disabling fast boot solved it too

**Comment by dartraiden** [comment] 2017-08-31 14:56
Confirm with Windows 10 1703. System favorites don't automount until Fast Boot is enabled.

**Comment by OstrichRider** [comment] 2017-12-28 05:08
The info about disabling fast startup to fix this issue needs to be displayed on the System Favorite Volumes manager where you can enable auto-mounting. Even better, VeraCrypt should be able to disable it for you. I wasted a good hour trying to figure out why my volume wasn't mounting automatically.

**Comment by Sina-h** [comment] 2018-04-14 09:02
My system favorite successfully mounts about 30% of the time.
Faststart is off. I suspect it's because my keyboard language is Norwegian vs. ENG.
When drive successfully mounts I have to manually change back the language to NOR for my own use.
When it fails the language never changes to ENG at all.

Windows event error:
The default transaction resource manager on volume A: encountered a non-retryable error and could not start.  The data contains the error code.

**Comment by xpac1985** [comment] 2018-04-18 22:39
I came here, because I experienced the same again, but only the last few days. Turns out that changing the power saving plan lately had reset Windows to use Fast Boot again, which caused the issues. Turned it off again. :)
