### ISSUE TITLE
[BUG] VeraCrypt deletes a created container if user fails to mount it after creation.

### ISSUE THREAD

**Issue by supercom32** [veracrypt/VeraCrypt#345] opened 2018-07-30 17:17 UTC
Steps to reproduce.

1. Open "Veracrypt Volume Creation Wizard"
2. Select "Create an encrypted file container" and click Next
3. Select "Standard" and click Next
4. Select file location, such as "C:\test.container.db". Click Next.
5. Select any encryption options and click Next.
6. Proceed to creating your image.
7. After your image is created and the progress bar is at 100%, you will be prompted to mount your image (root password required).
8. Select cancel instead of entering a password.

BUG:

The created container gets deleted and the user must click on the "Format" button to do it again. For containers which are extremely large (ie. takes > 10 hours to create), this is quite painful. In addition, if the user specifies a correct password (but the mounting fails for any reason) the file will be deleted anyway.

Possible workaround (?): 

If your worried mounting will fail, after you create your disk image and are prompted for the root password, kill VeraCrypt to prevent it from deleting your container. Then launch VaraCrypt again and mount it normally. If the mounting fails (bad password, etc) you'll be able to try again like any normal container without the fear of it being deleted.

**Comment by cookieenabled** [comment] 2018-07-31 03:51
```
- 1-7. Same,
+ 1-6. Same,
```

> "you will be prompted to mount your image (root password required)"

No

**Comment by supercom32** [comment] 2019-09-30 15:00
Tested with the latest version of Veracrypt (1.23 Linux) and I can confirm this behavior still happens. If mounting the image fails for any reason (You take too long, wrong password, etc), you loose the entire container.

**Comment by alt3r-3go** [comment] 2019-10-22 18:32
I can't seem to reproduce this, in my case (Debian 9, just the first VM I had for other VC tests) at the end of the creation wizard it doesn't really ask me for root password for mounting, just proceeds with something that looks like a mount process and presents a "success" screen. The container is not mounted though when I close it, so I guess that mount is some sort of sanity check by the wizard, I haven't looked at the code yet. I can then mount it normally by specifying the path to container in the "Select file" dialog (or directly in the corresponding edit box). This is on 1.24-hotfix1-preview, but I think that doesn't matter much compared to 1.23 as I don't remember any fixes around that piece.

@supercom32, what's you Linux distro where you observe that?

**Comment by supercom32** [comment] 2019-10-22 20:20
@alt3r-3go: I'm currently using Ubuntu (I think 18.04 LTS, or the previous LTS). What I usually do to reproduce this is create a very large container (something in the TB range so it takes a long time). Let it create the container overnight. When you come back in the morning, you'll see that at some point after the creation was finished Veracrypt prompts you for a password to mount the container. However, because you let the dialog sit for so long, something becomes stale and it doesn't work anymore. If you cancel the dialog, you get some kind of error (I didn't take note of it at the time) and your container is deleted. I suspect even if you provided the right password, due to whatever happened it wouldn't work.

As a workaround, I found killing Veracrypt at this point works, and then you can launch it again and try to mount your container. You'll have to rebuild the filesystem manually for your container before you can use it, but at least it won't outright delete the whole thing.

**Comment by alt3r-3go** [comment] 2019-10-30 21:05
Understood, interesting. Looks like I'll need to take a look at the code then, would be faster.

**Closed** 2021-01-06 08:32 UTC
Labels: wontfix

**Comment by simulated-tea** [comment] 2022-09-28 13:50
I would like to note, that I still struggle with this issue.
Arch Linux (Manjaro) and a VeraCrypt 1.25.9

I don't get any request to mount the container. (It is created with only a key file for a secret.)
It only shows a 'success' Popup and goes on to delete the container even before I can click the 'OK' button.

This is quite annoying.

**Comment by gitdgv** [comment] 2024-02-28 18:56
simulated-tea:
"I would like to note, that I still struggle with this issue.
Arch Linux (Manjaro) and a VeraCrypt 1.25.9

I don't get any request to mount the container. (It is created with only a key file for a secret.)
It only shows a 'success' Popup and goes on to delete the container even before I can click the 'OK' button.

This is quite annoying."

Feb 2024, linux mint, still the same issue (1.26.7)
