### ISSUE TITLE
VeraCrypt does not update the Date Modified for containers

### ISSUE THREAD

**Issue by sukhoi47** [veracrypt/VeraCrypt#209] opened 2017-09-16 17:46 UTC
Hi,

I am running **VeraCrypt 1.21 64 bits** version on my Windows 10 Pro x64 with all updates.
The computer runs smooth without any issue.
VeraCrypt is installed as a regular software, instead portable.
Containers are in a NTFS partition and they have no hidden containers.

I have a number of VeraCrypt containers named like "mycontainer.hc".
I can mount, dismount and perform all regular operations with files inside the containers without any problem.

The problem is... the **mycontainer.hc** file "**Date Modified**" property registered on the file system and visible with Windows Explorer is not updated.
The **Date Modified** remains the same as **Date Created**, does not matter how much I change the files inside the container.

This problem is tricking my backup software that is assuming **mycontainer.hc** was not changed and, because of that, the latest container file version is not backed-up.

I can set my backup software to force the backup for containers, but that is not a good solution for many reasons:
- because some containers are changed while others are not changed, since last backup. Backup unchanged containers implies in a huge waste of time and unnecessary wearing of backup media. 
- disrupt my backup routines and procedures.

I think many people doing backup for containers are not even aware of such problem.

**Comment by Eyremba** [comment] 2017-09-16 17:49
That's fully intentional.

VeryCrypt resets the modify and the last access date everytime, to leave no hints for attackers.

As far as I know, this can't be disabled in the current versions.

Maybe there will be a config option for that later, if the author of VeraCrypt implemets this.

**Comment by panther2** [comment] 2017-09-16 20:17
There has been and is a setting that can be disabled in order to get the **Date modified**:

![vc](https://user-images.githubusercontent.com/20812775/30515675-d07dabf0-9b2c-11e7-97cd-1e8d9085b776.gif)

**Comment by sukhoi47** [comment] 2017-09-17 19:55
Thanks for the info, @panther2.

All set now!

**Comment by sir106** [comment] 2018-03-17 05:38
I tried this, but this has no effect (veracrypt 1.21, 64-bit) - did anyone suceed on this?

**Comment by jncraton** [comment] 2018-05-05 23:05
You can also avoid having the modified time overwritten by mounting with `--mount-options=timestamp` from the command line. That's working for me currently, but I'm still on 1.17.

**Comment by metal450** [comment] 2018-06-04 21:49
I'm also having this issue with regards to backup software, also tried Preferences->Preserve modification timestamp=disabled, and like sir106 noted, it seems to have no effect either way. I still see no way to ensure that my modified containers get backed up.

I've googled around and found a number of other forums w/ users expressing the same issue (i.e. https://www.tenforums.com/antivirus-firewalls-system-security/91468-veracrypt-container-timestamp-wont-change.html)

**Comment by Bender-** [comment] 2018-11-07 22:16
Hi everyone,

for those waiting for a fix for this. I experience the same issue when checking that option in the GUI. The container date does not change. However i am using the commandline to mount my container and use the option "/m ts" and there it is working for me now.   (Veracrypt 1.22 64-Bit)

Notice: I only mount via commandline and the parameter. When i dismount i still use the gui for that.

This is the full commandline i use:

"C:\Program Files\VeraCrypt\veracrypt.exe" /q  /l s /m ts  /v d:\_data\prg_conf_data\Alf-BanCo\<filename>.<extension>

/q for quiet mode
/l s for setting the drive letter, in this case s
/m to disable protecting the timestamp
/v ...  the containerfile to be mounted

**Comment by sukhoi47** [comment] 2018-11-11 13:29
This subject has been clarified!
The non-changing date is an intended security feature that can be turned off/on in the VeraCrypt settings.

Check the post written by @panther2 that has an animated GIF file showing how to turn off/on. Here is the direct link to such comment:
https://github.com/veracrypt/VeraCrypt/issues/209#issuecomment-329992402

**Comment by wbrells** [comment] 2018-11-11 14:48
Folks,

I've found, like several other users, that the "Preserve modification timestamp of file container" option in the VeraCrypt **GUI** does not appear to work. If the **GUI** is used to mount a volume the modification timestamp never gets changed regardless of the above-mentioned option. However, using the command line way of mounting a volume (see comment from Bender, above) DOES cause the modification timestamp to be updated appropriately. MY PROBLEM is just that the modification timestamp is INCORRECTLY updated when all I do is mount a volume and DON'T update any files! I'm hoping there is some way to keep this from happening & to PREVENT the 'mount' operation from updating that timestamp...

Wayne

**Comment by wbrells** [comment] 2018-11-12 11:56
Folks,

Now I'm very confused! In my latest testing it doesn't seem that using the command line to mount a VeraCrypt volume really helps with the "date modified" problem! Also, I noticed in at least one case just dismounting a volume (using the GUI) caused the "date modified" to get updated. In other words, VeraCrypt seems VERY ERRATIC when it comes to when/if it updates the "date modified" time!

Does anyone have a better insight as to what is happening when it comes to VeraCrypt and "date modified"?

Thanks, Wayne

**Comment by pacproduct** [comment] 2020-02-25 19:53
Was facing the same issue for backing-up the container.

I'm on 64-bit version 1.24-Hotfix-1 and unchecking the checkbox "Preserve modification timestamp of file containers" as mentionned in https://github.com/veracrypt/VeraCrypt/issues/209#issuecomment-329992402 did do the trick for me too. Cheers.

Although I think this label could be clarified because I wouldn't have guessed what it does on my own. Thanks for the tip!

**Comment by alt3r-3go** [comment] 2020-03-15 17:42
All, this (preserving the timestamps on containers) is actually a standard feature of VC, enabled by default, in order to be more privacy-oriented. @idrassi, based on apparent non-zero popularity of this issue, do you think it would be helpful to elaborate on this a bit in the docs? I currently see a mention in CLI version docs only ([here](https://github.com/veracrypt/VeraCrypt/blob/master/doc/html/Command%20Line%20Usage.html#L166)).

**Comment by MyCoolAnvil** [comment] 2020-05-07 15:07
Unfortunately having read this and other threads I am still experiencing an issue with Veracrypt not updating the modified date on the volume file.

In my instance this was something that was previously working but then suddenly stopped (i'm not sure if it was related to a Windows 10 update).  It stopped working a while ago (probably over a year) but didn't have the time to investigate until today.  I have tried all of the following:

- Un-checking "Preserve modification timestamp of file containers" on GUI
- Updating/observing "PreserveTimestamps" as 0 in Configuration.xml
- Command Line with "/m ts" option
- Updating Veracrypt (was 1.23-Hotfix-2, now 1.24-Update6)
- Creating a new volume

In all instances the modified date remains unchanged after the contents of the volume have been modified and the drive dismounted.

Any ideas on what my issue might be?  As mentioned I'm on Windows 10 Pro (running the most recent updates).

Thanks,

Michael.

**Comment by egorshulga** [comment] 2020-05-15 16:53
I have "Preserve modification timestamp of file containers" flag unchecked, and still timestamps are not modified.

**Comment by MyCoolAnvil** [comment] 2020-05-15 19:28
Just an update from my [post](https://github.com/veracrypt/VeraCrypt/issues/209#issuecomment-625313166) above but the modified date started to update a couple of days later.  Whether it was the fact that I restarted Windows in between, I don't know.  This was with Veracrypt 1.24-Update6 - I have a desktop still running 1.23-Hotfix-2 and confirmed that this version still doesn't work.

Note however that whilst 1.24-Update6 now updates the modified date, I have observed what others have stated about it being updated every time you dismount regardless of whether the volume has been modified or not.  This is far from ideal when sync'ing across devices as the most recently accessed will seem like the most up to date version when this might not be the case, resulting in data loss.

I think enough people are reporting issues with this flag that it should be investigated by VeraCrypt.

**Comment by alt3r-3go** [comment] 2020-05-30 16:10
@MyCoolAnvil, let's split this to make sure the specific issue to fix (if any) is isolated. What do you think should be investigated/fixed
1. The fact that the timestamp is *not* updated (which seems to be actually not an issue for the latest 1.24-Update6 as you have found out yourself)
1. The fact that the timestamp is always updated, even if the user seemingly hasn't done any volume modifications? Please note that this one can actually be a side effect of the OS doing some housekeeping, indexing, creating thumbnails or something like antivirus checking stuff and modifying access timestamps - all behind the scenes from the user's point of view.

**Comment by MyCoolAnvil** [comment] 2020-06-05 15:28
Hi @alt3r-3go,

As you state it seems that the timestamp is in fact being updated now with the latest version of VeraCrypt so this appears to be resolved.

With regards to the timestamp always updating, I'm not sure this is down to the OS or antivirus software.  I've observed that if I mount the volume and then immediately dismount (without ever accessing the mounted drive) then the modified time changes.  I think this is definitely something that needs investigated as this could lead to data loss when sync'ing across multiple locations.

**Comment by agupta1979** [comment] 2020-12-18 15:53
I am using older version 1.21....the issue does not exist.  
 - if we check the preference, then no matter what you do, the timestamp does not change
 - if we uncheck the preference then
 -   a. if we open the volume and dont do any modification, the timestamp does not change
 -   b. if we do some changes, the timestamp changes.
I guess till a definite solution arrives, its better to downgrade !

**Comment by alt3r-3go** [comment] 2020-12-20 13:58
@agupta1979, what about the current release, does on the same system where you tested 1.21, step 2a in your list actually change the timestamp for you?

**Closed** 2021-02-25 14:57 UTC
Labels: wontfix

**Comment by grahamkeen** [comment] 2021-06-20 12:42
This issue still exists for me even though I am using V1.24 Update 7 (64bit)
The unchecking of the preference has no effect.
Regards,
Graham.

**Comment by rune-b** [comment] 2021-07-07 10:30
@grahamkeen I just unchecked this preference and now the modified date updates for me. But not until I actually changed a file in the volume. Just mounting it did not alter the date.

Using 1.24-Update6 (64 bit), Windows 10

**Comment by gety9** [comment] 2022-01-16 21:08
VeraCrypt 1.24-Update7 (64-bit), Windows 10 Pro

Unchecking "Preserve modification timestamp for file containers" updates Date Modified

-, on file changes (good)

-, on any open/close of container (bad)

2nd part is the issue.

**Comment by gety9** [comment] 2022-01-16 21:09
VeraCrypt 1.24-Update7 (64-bit), Windows 10 Pro

Unchecking "Preserve modification timestamp for file containers" updates Date Modified

-, on file changes (good)

-, on any open/close of container (bad)

2nd part is the issue.

**Comment by Vinfall** [comment] 2022-05-02 10:12
> But not until I actually changed a file in the volume. Just mounting it did not alter the date.

@rune-b  Did you just mount the volume and unmount it without data being READ? As mentioned by @wbrells, VeraCrypt should not update the timestamp by just "reading" the file (instead of "writing"/"overwriting").

The followings are tested on VeraCrypt 1.25.9 on Windows 10. Just mounting & unmouting the volume does not change the timestamp, which is good. However, **accessing the volume without modification should not update the timestamp**.

| Checking `Preserve modification timestamp for file containers` | File | Timestamp | Result |
| :--------  | :-----  | :----:   | :----:  |
| Yes | No read or overwritten | Preserved | Good |
| Yes | Read | Preserved | Good |
| Yes | Overwritten | Preserved | Good |
| No | No read or overwritten | Preserved | Good |
| No | Read | Changed | Bad |
| No | Overwritten | Changed | Good |

**Comment by alexagranov7** [comment] 2023-11-24 23:00
I'm using 1.26.7(64-bit) on Windows 11. How can I get the container timestamp to update so that my backup software picks it up?

**Comment by Vinfall** [comment] 2023-11-25 02:22
It's mentioned above but anyway, Settings -> Preferences -> **Uncheck** `Preserve modification timestamp of file container`. Or alternatively you can switch to a [backup solution](https://en.wikipedia.org/wiki/Comparison_of_online_backup_services) that supports [delta sync](https://en.wikipedia.org/wiki/Delta_encoding).

**Comment by thamulot** [comment] 2024-03-29 19:20
FYI - for the `Preserve modification timestamp for file containers` option to work, I had to initially restart the application after unchecking it. Please note that the modification date only change uppon unmounting the volume.

**Comment by Vinfall** [comment] 2025-02-02 02:58
I guess it's more of a filesystem (NTFS only?) design then, not sure if it would still happen on Linux when the volume is formatted as NTFS. I'm on Linux now and dm-crypt would just suffice anyway.
