### ISSUE TITLE
[MacOS - Sonoma 14.6] Crashing when open

### ISSUE THREAD

**Issue by mauroobento** [veracrypt/VeraCrypt#1397] opened 2024-08-12 21:05 UTC
Just installed the latest Veracrypt version (VeraCrypt_1.26.7) and the app is not even opening. It just shows a message 

```
# VeraCrypt quit unexpectedly.
Click Report to see more detailed information and send a report to Apple.
```

When I click in the Report button, I have this error here

```
Termination Reason:    Namespace DYLD, Code 1 Library missing
Library not loaded: /usr/local/lib/libfuse.2.dylib

Referenced from: <some random UUID> /Applications/VeraCrypt.app/Contents/MacOS/VeraCrypt

Reason: tried: '/usr/local/lib/libfuse.2.dylib' (fat file, but missing compatible architecture (have 'i386,x86_64', need 'arm64e' or 
'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/lib/libfuse.2.dylib' (no such file), '/usr/local/lib/libfuse.2.dylib' (fat 
file, but missing compatible architecture (have 'i386,x86_64', need 'arm64e' or 'arm64')), '/usr/lib/libfuse.2.dylib' (no such file, 
not in dyld cache), '/usr/local/lib/libmacfuse_i32.2.dylib' (fat file, but missing compatible architecture (have 'i386,x86_64', need 
'arm64e' or 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/lib/libmacfuse_i32.2.dylib' (no such file), 
'/usr/local/lib/libmacfuse_i32.2.dylib' (fat file, but missing compatible architecture (have 'i386,x86_64', need 'arm64e' or 
'arm64')), '/usr/lib/libmacfuse_i32.2.dylib' (no such file, not in dyld cache)

(terminated at launch; ignore backtrace)
```

Since there isn't a package for Intel and another one to Arm64 (which is mine, MBP M1), most likely this release is meant for Intel... is that right?

# Expected behavior
Open and use it properly

# Observed behavior
Crash and not opening 

# Steps to reproduce
1. Make sure you are running Sonoma 14.6 on a M1
2. Install the latest version available (1.26.7)
3. Try to run it 
4. Notice the error message

# Screenshots
<img width="277" alt="image" src="https://github.com/user-attachments/assets/bf4fdd3e-8ab8-4999-a60f-d28a608d9fa9">

# Your Environment

MacOS Sonoma 14.6 MPB M1

**VeraCrypt version:** 
1.26.7

**Operating system and version:**
MacOS Sonoma 14.6 MPB M1

**System type:** ARM64

**Comment by idrassi** [comment] 2024-08-12 23:10
The issue is caused by the presence of a FUSE library on your machine that is not valid for ARM64:

`/usr/local/lib/libfuse.2.dylib` (fat file, **but missing compatible architecture**: has 'i386, x86_64', needs 'arm64e' or 'arm64').

You installed something that brought this invalid library file (possibly via Homebrew).

VeraCrypt requires the presence of MacFUSE (or FUSE-T in the latest code), which are compatible with ARM64.

The easiest solution for you is to install FUSE-T (https://www.fuse-t.org/) and then install version 1.26.12 of VeraCrypt, which is dedicated to FUSE-T and which I published in this comment (https://github.com/veracrypt/VeraCrypt/issues/1055#issuecomment-2185317799) and at https://sourceforge.net/projects/veracrypt/files/VeraCrypt%20Nightly%20Builds/macOS/.

You can also install MacFUSE (https://osxfuse.github.io/), but it requires booting your M1 machine into recovery mode to enable it, as described at https://eengstrom.github.io/musings/install-macfuse-and-sshfs-on-macos-monterey. The complexity of this process is what drove the addition of FUSE-T support, which doesn’t require this. The advantage of MacFUSE is that the existing VeraCrypt 1.26.7 is compatible with it.

Both solutions will fix your issue. Just avoid installing or updating the software that brought the invalid libfuse library to your machine.

**Comment by idrassi** [comment] 2024-08-19 04:50
Closing this issue as fixed. Please feel free to reopen if you still have the problem after following the solutions provided.

**Closed by idrassi** 2024-08-19 04:50 UTC
Labels: bug

**Comment by mauroobento** [comment] 2024-08-20 16:48
Superb @idrassi ... Just installed `VeraCrypt_FUSE-T_1.26.13` but now I realized Truecrypt format are no longer available... 

((insert Aladeen gif with ""very nice"" captions))

**Comment by idrassi** [comment] 2024-08-20 20:03
Indeed, TrueCrypt support was removed. You can convert TrueCrypt volumes to VeraCrypt using version 1.25.9, but you will need to downgrade and also install macFUSE. The documentation contains topics on the conversion process:

- [Converting TrueCrypt volumes and partitions](https://veracrypt.fr/en/Converting%20TrueCrypt%20volumes%20and%20partitions.html)
- [Conversion Guide for VeraCrypt 1.26 and Later](https://veracrypt.fr/en/Conversion_Guide_VeraCrypt_1.26_and_Later.html)

Installing macFUSE on an M1 Mac is complicated but it’s currently the only way to proceed on macOS if you need to convert TrueCrypt volumes to VeraCrypt using version 1.25.9.

For Windows, I implemented a standalone tool that allows for the conversion of TrueCrypt volumes. I plan to do the same for macOS and Linux but I’m not sure when I’ll be able to work on it.

**Comment by mauroobento** [comment] 2024-08-21 16:58
Superb! Gonna give a shot then!! 

Thanks =)

**Comment by architectural27** [comment] 2024-09-20 22:39
> The easiest solution for you is to install FUSE-T (https://www.fuse-t.org/) and then install version 1.26.12 of VeraCrypt, which is dedicated to FUSE-T and which I published in this comment ([#1055 (comment)](https://github.com/veracrypt/VeraCrypt/issues/1055#issuecomment-2185317799)) and at https://sourceforge.net/projects/veracrypt/files/VeraCrypt%20Nightly%20Builds/macOS/.

Does it mean we shouldn't update VeraCrypt (if we want to use FUSE-T)?
Will the FUSE-T version of VeraCrypt ever be merged with the latest release?

**Comment by idrassi** [comment] 2024-09-21 04:59
FUSE-T support is now part of official VeraCrypt release: the [download page](https://veracrypt.fr/en/Downloads.html) provides direct link to download FUSE-T version of VeraCrypt.
So just download it and install it.

**Comment by architectural27** [comment] 2024-09-23 18:50
Thank you.
The issue I was encountering is that I was using brew to install VeraCrypt (which installs the OSXFUSE version).
Installing from download page solved the problem.
