### ISSUE TITLE
1.22 on Win10 1709 - unable to unmount container, unable to close VeraCrypt

### ISSUE THREAD

**Issue by hartacus** [veracrypt/VeraCrypt#314] opened 2018-04-26 03:27 UTC
Unable to unmount container (created with default options) on Win10 using VeraCrypt 1.22.

VeraCrypt hangs (CPU usage negligible). Unable to close VeraCrypt process through Task Manager. Computer unable to restart because VeraCrypt won't close - hard reset required.

On re-mounting, error about container not being unmounted/possible file system damage (though no damage observed).

Seems similar to issue #295 and/or #208, but I've tried all troubleshooting steps in those tickets to no avail. Please let me know if further information is required.

**Comment by idrassi** [comment] 2018-04-26 05:35
Your issue is different from #295 and #208 (first one is related to
secure desktop which doesn't occur on dismount and second one is about
waiting dialog but this is normally fixed in 1.22 and you already
disable waiting dialog with no change).

The hang is most probably caused by the fact that VeraCrypt is waiting
for data to be flushed to the container after some data was written to
it. Flushing is done by Windows kernel and we can't control when it will
finish.

To be sure, do you reproduce the hang without writing any data to the
container?

**Comment by hartacus** [comment] 2018-04-26 05:56
Yes, it happens both with and without writing any data to the container. I've also tried creating a new smaller container and experienced the same issue with a much smaller amount of data written.

**Closed** 2021-01-06 11:32 UTC
Labels: wontfix
