### ISSUE TITLE
Auto-mount fails on Mint 18.2

### ISSUE THREAD

**Issue by fullofcaffeine** [veracrypt/VeraCrypt#244] opened 2017-11-28 18:46 UTC
Hi there!

First of all, thanks for Veracrypt. I've been searching for a good cross-platform (filesystem/OS-wise) encryption solution for a good while, and Veracrypt seems to be it :)

I succesfuly formatted and encrypted an external USB3 2TB hard-drive using NTFS and the default encryption settings. I can manually mount it without any issues whatsoever, but I just can't get `automount` to work. Veracrypt just hangs there for a good while until it shows me the following message:

![foobar](https://user-images.githubusercontent.com/81248/33337848-eeeb5902-d439-11e7-849f-447c6d81fef9.png)
_(Apologies for the black rect artifact there, for some unkwown reason it was captured when I created the screenshot)_

I'm sure the password is the right one. Do you happen to know what could be wrong?

I'm using Linux Mint 18.2 on a Dell XPS 15 9550. If you need further system specs, let me know.

Thanks in advance.

**Comment by idrassi** [comment] 2017-11-29 16:37
I was able to reproduce the issue on Linux Mint 18.
The cause was a strange failure of the system function "open" when called on a partition which would return error ENOENT (No such file or directory) if it was called previously on the main disk. For example, if we call open("/dev/sda1") directly, it will work but if we call open("/dev/sda") and then open("/dev/sda1"), the later will fail with ENOENT.

Clearly, there is something wrong here at system level (glibc issue or kernel issue). To workaround this, I made a change in VeraCrypt to avoid trying to mount a disk device if it has partition and try directly to mount its partitions instead. The corresponding commit is https://github.com/veracrypt/VeraCrypt/commit/668d5e3cad96a0dc79377d8c2dfba4ae600e483c.

Are you able to build VeraCrypt yourself in order to check that indeed it fixes the error on your side? Otherwise, I can share with you a build to do the test.

Thank you for reporting this.

**Comment by fullofcaffeine** [comment] 2017-11-29 18:51
Yes, I can build Veracrypt, I will try it out over the weekend. Thanks a bunch for the quick response and for looking into it!

**Comment by idrassi** [comment] 2017-12-09 14:16
I have published installers for 1.22-BETA4 that contains the fix. You can get them from https://sourceforge.net/projects/veracrypt/files/VeraCrypt%20Nightly%20Builds/.

Closing this issue. Please feel free to reopen if you still have problems.

**Closed by idrassi** 2017-12-09 14:16 UTC

**Comment by fullofcaffeine** [comment] 2017-12-18 17:52
Thanks! 🙇
