### ISSUE TITLE
Cannot copy file encrypted with EFS

### ISSUE THREAD

**Issue by gamesharkmike** [veracrypt/VeraCrypt#123] opened 2016-12-22 17:09 UTC
If I want to copy a file that is encrypted with EFS to a VeraCrypt volume I get an error.

![image](https://cloud.githubusercontent.com/assets/6124851/21433877/e06c318e-c82e-11e6-8bad-ff8f29b376ce.png)

**Comment by idrassi** [comment] 2016-12-22 22:37
Are you running the latest 1.19 version? 
There was a similar issue under Windows 10 when the system is fully encrypted with VeraCrypt and it was fixed on 1.19. What is your configuration?
Maximum details are needed to reproduce and fix.

**Comment by JackTrapper** [comment] 2017-10-28 00:22
Has any developer has even **attempted** to reproduce it? Has anyone tried to copy an EFS encrypted file to a VeraCrypt volume formatted with NTFS. Have you even **attempted** it? Because you can see it fail quite easily for yourself. Instead it seems you simply read the issue reported by someone else, look at it really hard, and give up.

From the [SourceForge page where i already did all the work for you:](https://sourceforge.net/p/veracrypt/tickets/94/)

------------------------------------------------

I guess i have to beat the devs over the head with steps to reproduce.

Steps to reproduce
-------------

1. Create a test file
     - Create a file called **HelloWorld.txt** on an NTFS formatted volume
     - Open the file in **Notepad**, and enter the contents `"Hello, world!"`
     - Save the file, and close notepad

2. Encrypt the file using NTFS encryption
     - Right click the file **HelloWorld.txt** in Windows Explorer, and select **Properties**
     - On the **General** tab, click the **Advanced** button
     - Check the **Encrypt contents to secure data** checkbox
     - Click **OK** to close and **Advanced attributes** dialog box
     - Click **OK** to close the **HelloWorld.txt Properties** dialog box

3. Copy the NTFS EFS encrypted file to a Veracrypt mounted partition
    - Right click the file **HelloWorld.txt** in Windows Explorer, and select **Copy**
    - In Windows Explorer, navigate to a mounted, NTFS formatted, Veracrypt volume
    - Right-click in the Windows Explorer file list, and select **Paste**
    - Notice the error *Invalid MS-DOS function*

![](http://i.imgur.com/fU4eq1y.png)

To eliminate any blame of Explorer, i created a sample program that simply does:

    CopyFile("c:\temp\HelloWorld.txt", "f:\HelloWorld.txt", false);
    
The function fails, and GetLastError returns ERROR_INVALID_FUNCTION (1): *"Incorrect function"*

Using Process Monitor reveals a call to **DeviceIOControl** with the IOCTL [`IOCTL_MOUNTDEV_QUERY_DEVICE_NAME`](https://msdn.microsoft.com/en-us/library/windows/hardware/ff560437.aspx). The function call fails with **Invalid Parameter**.

From [MSDN](https://msdn.microsoft.com/en-us/library/windows/hardware/ff560437.aspx):

> Support for this IOCTL by the mount manager clients is ***mandatory***. Upon receiving this IOCTL a client driver **must** provide the (nonpersistent) device (or target) name for the volume. The mount manager uses the *device name* returned by the client as the target of a symbolic link. An example of a device name would be "\Device\HarddiskVolume1".

*(Emphasis mine)*

You can see the stack trace chain leading up to the `DeviceIOControl`:

Module | Function
---------- | ---------- 
KERNELBASE.dll | DeviceIOControl
KERNELBASE.dll | GetVolumeNameForRoot
KERNELBASE.dll | GetVolumePathNameInternalW
KERNELBASE.dll | GetVolumePathNameW
feclient.dll | EfspGetFullName
feclient.dll | CEfsClientBase::LocateAndConnectToService
feclient.dll | CEfsClientBase::EfsFileKeyInfoClient
feclient.dll | EfsClientGetKeyInfo
feclient.dll | EfsClientGetEncryptedFileVersion
KERNELBASE.dll | Tbsi_Physical_Presence_Command
KERNELBASE.dll | BasepCopyFileW
KERNELBASE.dll | CopyFileExW
KERNELBASE.dll | CopyFileW
TestVeraCryptBug.exe | TestVeraCryptBug.exe + 0x4e224

Now that i've done the hard work, can you please respond correctly to the **IOCTL_MOUNTDEV_QUERY_DEVICE_NAME** i/o control code when asked for it?

-----------------------

That was a year and a half ago. Today i was trying to use `cipher.exe` to *decrypt* a file located on a VeraCrypt volume. Ciper would report an error. Instead i had to copy the file to a non-VeraCrypt volume, decrypt it there, and then copy it back.

And it's caused by **the same thing**:

![image](https://user-images.githubusercontent.com/4681474/32129338-1b2aa710-bb54-11e7-8444-8a55a4978b1f.png)

Your device is being sent the IOCTL `IOCTL_MOUNTDEV_QUERY_DEVICE_NAME`, and you're responding with `INVALID PARAMETER` error code. When your device is asked a question: stop giving the wrong response.

From MSDN, *again*:

> IOCTL_MOUNTDEV_QUERY_DEVICE_NAME control code
> ----------
> **Support for this IOCTL by the mount manager clients is mandatory.*** Upon receiving this IOCTL a client driver must provide the (nonpersistent) device (or target) name for the volume. The mount manager uses the device name returned by the client as the target of a symbolic link. An example of a device name would be "\Device\HarddiskVolume1".

It's not optional; you ***must*** support this IOCTL. 

- stop not supporting it
- and support it

**Comment by JackTrapper** [comment] 2019-05-19 18:28
The solution if for the VeraCrypt driver to correctly respond to the `IOCTL_MOUNTDEV_QUERY_DEVICE_NAME` control code.

VeraCrypt already creates a **DeviceName** for the mounted volume (e.g. **VeraCryptVolumeQ**):

![](https://i.imgur.com/gr0AKd6.png)

Windows just wants you to return it when it asks for it:

    case IOCTL_MOUNTDEV_QUERY_DEVICE_NAME: {
    
       PMOUNTDEV_NAME name;
       
       
       UNICODE_STRING ntDeviceName; //e.g. "\Device\VeraCryptVolumeQ"

         Status = WdfRequestRetrieveOutputBuffer(Request, OutputBufferLength, &name, NULL);
            if (NT_SUCCESS(Status)) {
                RtlZeroMemory(name, OutputBufferLength);
                name->NameLength = ntDeviceName.Length;
                RtlCopyMemory(name->Name, ntDeviceName.Buffer,name->NameLength);
            }
            
Again, this is not *optional*. If you write a driver for Windows you are obligated to write it correctly. That means following the API contract laid down by Windows.

**Comment by idrassi** [comment] 2019-10-01 23:03
@JackTrapper :
VeraCrypt correctly handles IOCTL_MOUNTDEV_QUERY_DEVICE_NAME and it responds correctly to it as it can be shown with simple tracing or by just looking at the source code. What you are seeing here is that on some of your machines, there is an unknwon filter driver that places itself above VeraCrypt device drivers and which filters IOCTL_MOUNTDEV_QUERY_DEVICE_NAME calls. It is this unknown filter driver that returns an error when queried using IOCTL_MOUNTDEV_QUERY_DEVICE_NAME.
This unknown filter driver could come from your antivirus or from other software on your machine. To fix the issue, we will need to know what this filter driver is doing and what it is expecting. One hypthesis is that this unknown filter driver is expecting a physical device and it encouters an error when it finds that the VeraCrypt volume is a virtual one. Anyway, we can't do anything for this unless we know more about the software configuration of the machines where this problem happens.

**Comment by alt3r-3go** [comment] 2019-10-22 18:50
Just as a case in point - I've just run the test on a plain Win10 VM with no antivirus (besides standard Windows Defender with on-access scanning enabled) installed and there's no problem with copying the filw from EFS-encrypted folder into VC container.

It doesn't show much, but just as a "material proof" :) here's a screenshot. Left is an EFS-encrypted folder and right is a container mounted as disk A:

![image](https://user-images.githubusercontent.com/45139988/67319688-8ff3a480-f50d-11e9-9a37-ca77add68833.png)

**Closed** 2021-01-06 08:32 UTC
Labels: wontfix

**Comment by JackTrapper** [comment] 2024-11-15 23:54
The wontfix issue has been fixed: [Problem with EFS / Win10 / VeraCrypt](https://sourceforge.net/p/veracrypt/discussion/technical/thread/e4a3053c/#08e8)
