### ISSUE TITLE
Wrong file showing up

### ISSUE THREAD

**Issue by Mo-Gul** [veracrypt/VeraCrypt#860] opened 2021-12-13 19:07 UTC
# Expected behavior

Show the right file in the file/volume text box (the one shown in the screenshot) (as in previous versions).

When double-clicking an HC file in the explorer window, it should show up in the file text box. The same should be true when selecting a file from "windows search", i.e. hitting the Win key, typing the name of the HC file and selecting it from there.

# Observed behavior

The files either show up as `<correct path>\%1` (A.) or `C:\Windows\system32\%1` (B.), depending on how the file was selected.

# Steps to reproduce

I observed two ways to produce wrong file names showing up.

A. Double-click HC file in explorer window
B. Choose file from Windows search
   1. hit Windows key
   2. type the filename you are searching for
   3. select the HC file either by clicking on it or by selecting it with the keyboard

# Screenshots

Screenshot of the result of B.

![image showing part of the VeraCrypt window](https://user-images.githubusercontent.com/17992976/145871854-a5dacc88-92e3-4221-9d78-3232cf294e89.png)

# Your Environment

Please tell us more about your environment

**VeraCrypt version:** 1.25.4 (64-bit)

**Operating system and version:** Windows 10 Version 21H1 (Build 19043.1348)

**System type:** 64-bit

**Comment by patrick258** [comment] 2021-12-23 20:19
confirmed the same issue on Windows 10 21H2 (build 19044.1415) with CV 1.25.4 (64) msi installer

**Comment by idrassi** [comment] 2021-12-27 16:06
Thank you for this report.
This is caused by a bug in the MSI installer that writes extra `%` character in the default value of the registry key `HKEY_CLASSES_ROOT\VeraCryptVolume\Shell\open\command`.

This issue will be fixed. Meanwhile, you can manually fixed by opening the above registry key in Regedit and then remove the extra `%`, thus replacing `"C:\Program Files\VeraCrypt\\VeraCrypt.exe" /v "%%1"` by `"C:\Program Files\VeraCrypt\VeraCrypt.exe" /v "%1"`.

For convenience, I'm attaching a zip file containing a .reg file to run to the fix the issue and its PGP signature.
[VeraCryptVolume_hc.zip](https://github.com/veracrypt/VeraCrypt/files/7780890/VeraCryptVolume_hc.zip)

A new version will be published this week to fix this issue.

**Closed** 2022-03-04 04:12 UTC
Labels: bug
