### ISSUE TITLE
VeraCrypt::BootEncryption::CreateRescueIsoImage:3439

### ISSUE THREAD

**Issue by jkl777** [veracrypt/VeraCrypt#441] opened 2019-04-07 09:16 UTC
I have te problem with W10 1809. I had to decrypt my SSD in order to apply this update. After that I cannot encrypt system drive because this error:

Parameter incorrect.

(If you report a bug in connection with this, please include the following technical information in the bug report:
VeraCrypt::BootEncryption::CreateRescueIsoImage:3439)
Tried all latest VC plus beta editions. Nothing. Only error code changes.

**Comment by GH-Rake** [comment] 2019-07-17 23:29
If you are still having problems please [read this thread](https://sourceforge.net/p/veracrypt/discussion/general/thread/0135ebe7/), you will find some relevant information.  Also there have been new beta versions since the date you posted this issue, there has been 1 relevant fix that I can find related to this error, perhaps it will fix it for  you.

**Comment by alt3r-3go** [comment] 2019-09-02 19:16
@jkl777, have you had a chance to check out the thread @GH-Rake referred to? Do you still have the same problem? If yes, please post the VeraCrypt version you've tried and the exact error message + error code you observe.

**Comment by jkl777** [comment] 2019-09-03 21:48
Still error - 1.24 Beta5

![vc_error](https://user-images.githubusercontent.com/49362000/64211038-2d830e00-cea5-11e9-8ce4-7c0a5da1f5e9.png)

**Comment by alt3r-3go** [comment] 2019-09-04 20:10
Thank you. I'll take a look at this then.

Just to make sure - that Windows update you mentioned in the description (the one for which you decrypted the drive) was *from* 1809 (to 1903, though April sounds a bit too early for that one) or *to* 1809 (from 1803)?

**Comment by jkl777** [comment] 2019-09-04 20:22
Sorry but I dont remember (but I think you are right). Now I have 1903.

**Comment by alt3r-3go** [comment] 2019-09-05 18:34
No worries, thanks.

**Comment by alt3r-3go** [comment] 2019-10-22 20:00
I'm now trying to reproduce this. Got a Win10 VM, version 1607 with VC 1.24 (not hotfix 1) installed and the system encryption is in progress. Pre-test worked fine. I'll do two tests after that:
1. Upgrade the VC to hotfix1-preview
1. Upgrade the Windows itself to newer version (whichever oneit will allow me to, not sure if it only allows the last one, i.e. 1903 or a sequence of 1607->whatever was in between->1903).

to see how it behaves. This is not a 100% exact thing you have, but generally is in the same ballpark, so we'll see.

**Comment by jkl777** [comment] 2019-10-26 20:35
> I'm now trying to reproduce this. Got a Win10 VM, version 1607 with VC 1.24 (not hotfix 1) installed and the system encryption is in progress. Pre-test worked fine. I'll do two tests after that:
> 
> 1. Upgrade the VC to hotfix1-preview
> 2. Upgrade the Windows itself to newer version (whichever one it will allow me to, not sure if it only allows the last one, i.e. 1903, or a sequence of 1607->whatever was in between->1903).
> 
> ...to see how it behaves. This is not a 100% exact thing you have, but generally is in the same ballpark, so we'll see.

Don't bother. I have found a solution :-)

Problem is with my account name, which is my name and surname (example John Doe). In my name I have Polish sign Ł (&#322;). I made new account JD and RescueDisc verification went fine.

You have to chceck code for windows path and account names while rescue disc making process.

**Comment by idrassi** [comment] 2019-10-27 00:35
@jkl777 : Thank you very much for sharing the workaround, it was very helpful in finding the real cause of the issue which was indeed a block of code that didn’t handle Unicode paths correctly. I have pushed a fix for it (https://github.com/veracrypt/VeraCrypt/commit/94084525b1a16b8c8721716a6bdc96d5a65a00fd) and this will be included in the upcoming 1.24-Hotfix1 version.

**Closed** 2019-10-27 23:06 UTC

**Comment by alt3r-3go** [comment] 2019-10-30 21:07
#181 could probably be closed as well then.
