### ISSUE TITLE
Cannot boot to hidden OS after 1.21

### ISSUE THREAD

**Issue by adamclaude00** [veracrypt/VeraCrypt#190] opened 2017-07-14 17:14 UTC
Hello.

I recently upgraded from 1.19 to 1.21.
First I upgraded on the outer OS then when attempting to boot into the hidden OS it would get stuck at Verifying Password. It doesn't return any error, it doesn't freeze (the " ... " still animates), it will just hang at verifying, I left it for 3 hours to see if anything would happen, no change.

So I then booted from the rescue disk boot loader that is running 1.19 which worked.
Once I got in I upgraded the hidden OS Veracrypt to 1.21 in hopes it would now work with the 1.21 boot loader, no luck, still hangs at verifying password.

Using the 1.19 boot loader from the rescue disk I was able to get back in so the volume header and drive is fine.

During the upgrades of both OS there were no errors, it all reported as being successful.
The only issue is with the hidden OS, the outer OS boots fine.

**Comment by idrassi** [comment] 2017-07-21 22:34
Hi,

After some investigations, it turns out that 1.21 MBR bootloader uses more stack memory than 1.19 one. This was caused by an erroneous addition of an unused extra field in Twofish structure.
This has been fixed in this commit (https://github.com/veracrypt/VeraCrypt/commit/3bdb9a32d78a644940f496570b58d3912180a486).
Moreover, I have done extra review of bootloader source code and I was able to reduce memory usage even compared to 1.19 (see https://github.com/veracrypt/VeraCrypt/commit/ff871511af79fd8fb7a09d3ed42220830e6ddcd6).

To check if this fixes your issue, can you please test the new 1.22-BETA using the installer at https://www.veracrypt.fr/downloads/1.22-BETA/VeraCrypt%20Setup%201.22-BETA2-Build0.exe (pgp signature at https://www.veracrypt.fr/downloads/1.22-BETA/VeraCrypt%20Setup%201.22-BETA2-Build0.exe.sig).

Thank you.

**Comment by idrassi** [comment] 2017-07-23 13:01
The fix is confirmed to work (see https://sourceforge.net/p/veracrypt/discussion/technical/thread/731d568a/?limit=25#a09a/c875/ba45/adba/c42a/64bd).

**Closed by idrassi** 2017-07-23 13:01 UTC
